### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by yuchaoran2011** [lyft/flinkk8soperator#18]
Hi authors of the operator,

We are a few engineers from Lightbend Inc. As operating Flink on K8s is part of our product goals, we are actively reviewing the potential usage of your Flink operator in our projects. We have a few questions about your implementation.

1) In the job manager config, the operator allows the user to configure the number replicas in the job manager Deployment. Could you elaborate on why this is allowed? For election of a new job manager, the k8s Deployment will automatically create a new job manager if the previous one is gone/dead. So it seems making the number of replicas always 1 suffices. Any scenarios when multiple replicas are needed in the Deployment?

2). The way the operator launches a Flink job is through uploading the application jar to a Flink cluster, which is created first. We are wondering why you don't simply tell the user to put the application jar on the Flink classpath (e.g. `$FLINK_HOME/lib`) when building the Docker image? Then there's no need for a separate step to upload the jar. It seems more straightforward that way.

Another issue that we've been looking at is Flink doesn't have native support for checkpointing on K8s. On K8s, we think the better alternative to do checkpointing (compared to using ZooKeeper) is to use a shared Persistent Volume Claim (PVC). From the standpoint of the job manager and task manager pods, checkpointing to a mounted PVC is the same as writing to a local file system. The PVC can be any technology that supports sharing (e.g. NFS, GlusterFS, and Portworx). But Flink itself doesn't yet support checkpointing to filesystem. We have done a PoC implementation for this feature. We will be looking at contributing it back to Flink. 

Would you guys be interested in having a conversation with us on potential collaborations on the operator and Flink on K8s?

**Comment by anandswaminathan** [comment]
Thanks @yuchaoran2011 for trying out.

Regarding (1), We plan to run Job managers with multiple replicas (mostly 2). This is mainly because, if there are issues to the current Jobmanager leader, we do not want wait to bring up another POD (which can be delayed due several reasons like load, etc), and for its container to start. With a standby jobmanager, we will have the new leader up, if there are issues with the existing Jobmanager. 

For (2), We do not upload the Jar to the cluster. In our current implementation, the operator only expects the Image able accept [Job submission](https://ci.apache.org/projects/flink/flink-docs-stable/monitoring/rest_api.html#jars-jarid-run) requests through API. In fact if you check out our [example](https://github.com/lyft/flinkk8soperator/blob/master/examples/wordcount/Dockerfile#L42), the jar is part of the image. More info here: https://github.com/lyft/flinkk8soperator/tree/master/examples

As you have mentioned, there are multiple ways to do Checkpointing. We at Lyft use Zookeeper internally, and hence have not tried out other alternative approaches. We would love to hear your thoughts and get contribution from you to the flink operator for any alternative approaches.

**Comment by yuchaoran2011** [comment]
Thanks @anandswaminathan for the clarifications. Yes I now see that job submission isn't a requirement for running a job.
We'll work on a PR on Flink itself to add support for checkpointing to a filesystem. We'll let you know when ready so that we can gather feedback from you.

**Comment by yuchaoran2011** [comment]
@anandswaminathan Would you and your team be interested in having a conference call with us?

**Comment by anandswaminathan** [comment]
@yuchaoran2011 Sorry I misunderstood. Job submission is not a requirement but I believe parts of the system will error out if Job is not part of the application spec. 

We have the job as part of the spec for multiple reasons - one big reason is updating job on the fly - arguments, parallelism, etc. Long term we might also add support for operator to detect and scale the cluster when needed.

**Comment by yuchaoran2011** [comment]
Yep I agree. That's the Flink job cluster mode (as opposed to the session cluster mode) that we are going to use.

**Comment by anandswaminathan** [comment]
@yuchaoran2011 Let's follow up through email (aswaminathan@lyft.com). We can setup sometime.

**Comment by yuchaoran2011** [comment]
@anandswaminathan Awesome! I'll shoot you an email later today.

**Comment by karula314** [comment]
Hi authors of the operator,  @anandswaminathan 

First thanks for providing this project as a great idea of managing Flink job on k8s . I'm an engineer working at Comcast and have  few questions about your implementation & design 
1.  on your example job , in docker entrypoint , you are starting jobmanager by using jobmanager.sh , but at Flink official job cluster mode it's using standalone-job.sh as entrypoint ,which needs job parameter to start Flink job manager .  Seems like your implementation is mostly likely start a session cluster and then submit a job on top of it ? what's the benefit of using this way to submit new job instead of directly start a job cluster ? 
2.  is there a way sync Flink job status to k8s CRD ? eg :  if a Flink job failed , does k8s CRD(FlinkApplication) updated automaticly ? 
3.  Do we also need to build a zookeeper for supporting Flink HA ? 

Thanks !

**Comment by yuchaoran2011** [comment]
@karula314 We have the same opinion as you regarding point #1. It seems unnecessary to start a Session Cluster first and then submit the job through a REST API. The job can be run in a Job Cluster using `standalone-job.sh`. This way, no separate submission step is needed.

**Comment by anandswaminathan** [comment]
@karula314 @yuchaoran2011 

For (1) We explicitly submit the Job on top because, that helps us make the job configurable. We can have one image that can be used to run multiple jobs. Users can update the job running in the cluster like arguments, parallelism without needing to build a new image. We are planning to add scale up support into the operator in future, the operator can then cancel and resubmit the job with new parallelism. The main reason for separating the job from the image is make the job running in the cluster configurable. We already have several applications which use the same image but run a different job underneath. 

For (2), We already update the Flink job status in the custom resource. Check [here](https://github.com/lyft/flinkk8soperator/blob/master/pkg/apis/app/v1alpha1/types.go#L133)

For (3), Yes. Right now we have a separate zookeeper cluster running, and the applications use it by setting values through [config](https://github.com/lyft/flinkk8soperator/blob/master/pkg/apis/app/v1alpha1/types.go#L34) in the custom resource

**Comment by karula314** [comment]
@anandswaminathan 
thanks for the quick reply , for #2 , I mean is it **automaticly** update the job status without calling any functions ? (like call updating or checking FlinkApplication) like monitoring your Flink job in realtime ?

**Comment by anandswaminathan** [comment]
@karula314 

Yes. The operator monitors all the applications and updates the status. The status updates happen on every operator callback during [resync](https://github.com/lyft/flinkk8soperator/blob/6fdd92f9762b6d023b446e0b04b66d1ba0e1443c/pkg/controller/config/config.go#L14)

**Comment by mwylde** [comment]
Just catching up on this conversation. It's great that lightbend is interested in the operator!

To clarify a few points:

* Zookeeper is not actually involved in checkpointing. Zookeeper is used for leader election when running jobmanagers in HA mode. In non-HA mode, cluster state (i.e., what jobs are running) is stored on a single job manager. If that's lost, the job will not be recovered. By using HA, the cluster state is stored in Zookeeper and can be recovered when a new JM comes up. This also allows you to run multiple JMs, which can potentially reduce downtime (this is less an issue on k8s, but on our legacy stack it can take >20 minutes to spin up a new JM node). For checkpointing, you can use any hadoop-compatible filesystem—at Lyft we use S3. This is specified as part of the file config (either built into the image or overriden in the FlinkApplicationSpec's flinkConfig field).
* As far as session cluster vs. job clusters, I'd be interested to hear the benefits of using the latter. We chose to implement session clusters initially because it allows the operator to control the job submission process more easily. My intuition is that it shouldn't really matter to the user which one is used, so I'd be interested to hear your usecase for wanting job clusters.

**Comment by yuchaoran2011** [comment]
@mwylde Thanks for the reply! 

About ZooKeeper, I should have made it more clear in my previous comment. We are actually looking to get rid of ZooKeeper for leader election in HA mode. My colleague @blublinsky create a [JIRA](https://issues.apache.org/jira/browse/FLINK-12751) and a prototype [implementation](https://github.com/apache/flink/pull/8637) to support filesystem-based HA. 

Regarding the benefits of the job cluster vs session cluster, they are mostly the following:
1. In the job cluster mode, there is no separate submission step involved. No REST API needs to be invoked to make the job run. That will result in a simpler and cleaner implementation in the operator (e.g. the operator doesn't need to verify that the REST endpoint is working and make sure the REST API call succeeds in submitting the job etc). One less step means one less thing to manage and one less thing that can potentially break.
2. An added small bonus for the user is that he doesn't need to pass the application jar name when running the job. Only the main class name is required. Flink automatically loads the right jar from the classpath. The only requirement is that the jar is placed somewhere on the classpath.

You are right that from a user's perspective, job cluster vs session cluster distinction isn't big at all. After discussions with @anandswaminathan, we have agreed to work with what the operator already has to offer for now.

**Comment by mwylde** [comment]
We've actually been thinking along similar lines for getting rid of zookeeper and managing state and failover within the operator. Our experience has been that the HA code in Flink is a bit immature, and we've seen a lot of issues around it. Very excited to see your progress on that!

**Comment by soumyasmruti** [comment]
Can the flink operator be used to deploy the jobs in `job cluster` mode instead of `session cluster`. I tried changing the docker `docker-entrypoint.sh` file to include `standalone-job.sh`instead of `jobmanager.sh` while starting the job manager. But I run into the following error. How can I navigate through this? Do we have to perform some changes in the code to facilitate job cluster?

```
2019-08-05 23:29:21,876 INFO  org.apache.flink.runtime.entrypoint.ClusterEntrypoint         - Shutting StandaloneJobClusterEntryPoint down with application status FAILED. Diagnostics org.apache.flink.util.FlinkException: Could not create the DispatcherResourceManagerComponent.
	at org.apache.flink.runtime.entrypoint.component.AbstractDispatcherResourceManagerComponentFactory.create(AbstractDispatcherResourceManagerComponentFactory.java:257)
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.runCluster(ClusterEntrypoint.java:224)
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.lambda$startCluster$0(ClusterEntrypoint.java:172)
	at org.apache.flink.runtime.security.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.startCluster(ClusterEntrypoint.java:171)
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.runClusterEntrypoint(ClusterEntrypoint.java:535)
	at org.apache.flink.container.entrypoint.StandaloneJobClusterEntryPoint.main(StandaloneJobClusterEntryPoint.java:111)
Caused by: org.apache.flink.util.FlinkException: Failed to find job JAR on class path. Please provide the job class name explicitly.
	at org.apache.flink.container.entrypoint.ClassPathJobGraphRetriever.getJobClassNameOrScanClassPath(ClassPathJobGraphRetriever.java:131)
	at org.apache.flink.container.entrypoint.ClassPathJobGraphRetriever.createPackagedProgram(ClassPathJobGraphRetriever.java:114)
	at org.apache.flink.container.entrypoint.ClassPathJobGraphRetriever.retrieveJobGraph(ClassPathJobGraphRetriever.java:96)
	at org.apache.flink.runtime.dispatcher.JobDispatcherFactory.createDispatcher(JobDispatcherFactory.java:62)
	at org.apache.flink.runtime.dispatcher.JobDispatcherFactory.createDispatcher(JobDispatcherFactory.java:41)
	at org.apache.flink.runtime.entrypoint.component.AbstractDispatcherResourceManagerComponentFactory.create(AbstractDispatcherResourceManagerComponentFactory.java:184)
	... 6 more
Caused by: java.util.NoSuchElementException: No JAR with manifest attribute for entry class
	at org.apache.flink.container.entrypoint.JarManifestParser.findOnlyEntryClass(JarManifestParser.java:80)
	at org.apache.flink.container.entrypoint.ClassPathJobGraphRetriever.scanClassPathForJobJar(ClassPathJobGraphRetriever.java:137)
	at org.apache.flink.container.entrypoint.ClassPathJobGraphRetriever.getJobClassNameOrScanClassPath(ClassPathJobGraphRetriever.java:129)
	... 11 more
```

**Comment by kevinkwoncareem** [comment]
I'm not sure if the job manager's only role is to elect the leader. Of what I understand, the Zookeeper also stores some metadata related to checkpoint (not the checkpoint data itself). I've tried terminating the jobmanager while a job is running on the cluster and it seems that the jobmanager starts from checkpoint 1 rather than the last checkpoint if HA mode is off

If all jobmanager fails in the Lyft Operator, I believe it will lose the metadata and not start from the last checkpoint. Refer to https://engineering.zalando.com/posts/2019/03/running-apache-flink-on-kubernetes.html as well

**Comment by fsw0422** [comment]
I'm not sure if the job manager's only role is to elect the leader. Of what I understand, the Zookeeper also stores some metadata related to checkpoint (not the checkpoint data itself). I've tried terminating the jobmanager while a job is running on the cluster and it seems that the jobmanager starts from checkpoint 1 rather than the last checkpoint if HA mode is off

If all jobmanager fails in the Lyft Operator, I believe it will lose the metadata and not start from the last checkpoint. Refer to https://engineering.zalando.com/posts/2019/03/running-apache-flink-on-kubernetes.html as well
