### ISSUE TITLE
Question: volumes/volumeMounts in the CRD

### ISSUE THREAD

**Issue by functicons** [lyft/flinkk8soperator#88]
I'm trying to understand volumes/volumeMounts in the [CRD](https://github.com/lyft/flinkk8soperator/blob/master/docs/crd.md). If I specify volumes/volumeMounts, are they available in every Pod including JobManager and TaskManager? What are the typical use cases? Can I specify different volumes/volumeMounts for my application, JobManager and TaskManager?

**Comment by anandswaminathan** [comment]
The volume and volumeMounts are passed directly to the Jobmanager and Taskmanager deployment, and hence every pod. 

It is not possible to specify different volume and volumeMounts for jobmanager and task manager. In order to do that, you will have to implement - [mutating admission controller webhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/) on your end.
